language: scala

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

scala:
   - 2.12.8
   
jobs:
  include:
    - stage: verify

      script:
        - sbt ++$TRAVIS_SCALA_VERSION todomvc/fullOptJS::webpack
        - sbt docs/mdoc
        - sbt docs/makeMicrosite
        - mkdir -p ex-docs/site/todomvc
        - cp -R ex-docs/target/site/* ./ex-docs/site/
        - cp ./ex-docs/site/Readme.html ./ex-docs/site/index.html
        - cp -R todomvc/assets/* ./ex-docs/site/todomvc
        - cp todomvc/target/scala-2.12/scalajs-bundler/main/outwatch-examples-todomvc-opt* ./ex-docs/site/todomvc/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ex-docs/site
  target-branch: gh-pages
  on:
    branch: master
  
