name: Outwatch Examples
baseurl: ''
description: A collection of examples demonstrating the outwatch scala.js virtual dom library
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: com.clovellytech
markdown: kramdown
