name: Outwatch Examples
baseurl: ''
description: A collection of examples demonstrating the outwatch scala.js virtual dom library
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1
org: com.clovellytech
markdown: kramdown
