'use strict';
var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=k;var m=exports;e.exportsNamespace=m;k.Object.freeze(e);var n={envInfo:e,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.26",globalThis:this};k.Object.freeze(n);k.Object.freeze(n.semantics);
var p=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},r=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},t=0,u=k.WeakMap?new k.WeakMap:null;function v(a){return function(b,c){return!(!b||!b.$classData||b.$classData.k!==c||b.$classData.i!==a)}}function aa(a){for(var b in a)return b}
function w(a,b,c){var d=new a.B(b[c]);if(c<b.length-1){a=a.l;c+=1;for(var f=d.z,g=0;g<f.length;g++)f[g]=w(a,b,c)}return d}function ba(a){switch(typeof a){case "string":return x(y);case "number":var b=a|0;return b===a?z(b)?x(A):B(b)?x(C):x(D):"number"===typeof a?x(E):x(F);case "boolean":return x(G);case "undefined":return x(H);default:return null===a?a.T():a&&a.$classData&&a.$classData.f.x?x(I):a&&a.$classData?x(a.$classData):null}}
function J(a){switch(typeof a){case "string":ca||(ca=(new K).d());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+p(65535&(a.charCodeAt(d)|0),c)|0,c=p(31,c),d=-1+d|0;return b;case "number":L||(L=(new M).d());b=L;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.g)b.C[0]=a,b=N(b.r[b.E]|0,b.r[b.D]|0);else{if(a!==a)b=!1,a=2047,c=+k.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+k.Math.pow(2,-1022)){a=+k.Math.pow(2,52);var c=
+k.Math.log(d)/.6931471805599453,c=+k.Math.floor(c)|0,c=1023>c?c:1023,f=+k.Math.pow(2,c);f>d&&(c=-1+c|0,f/=2);f=d/f*a;d=+k.Math.floor(f);f-=d;d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+k.Math.pow(2,-1074),c=+k.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=N(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.s^b.q}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||
null===a?a.w():null===u?42:ea(a)}}function fa(a,b){var c=k.Object.getPrototypeOf,d=k.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function ga(a,b,c){a=fa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function ha(a,b,c,d){a=fa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new k.TypeError("super has no setter '"+c+"'.");}
var ea=null!==u?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return J(a);default:if(null===a)return 0;var b=u.get(a);void 0===b&&(t=b=t+1|0,u.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;t=b=t+1|0;return a.$idHashCode$0=b}return null===a?0:J(a)};function z(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function B(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function O(){this.t=this.B=void 0;this.i=this.l=this.f=null;this.k=0;this.A=null;this.p="";this.b=this.n=this.o=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function P(a,b,c){var d=new O;d.f={};d.l=null;d.A=a;d.p=b;d.b=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function Q(a,b,c,d,f,g,l){var h=new O,q=aa(a);g=g||function(a){return!!(a&&a.$classData&&a.$classData.f[q])};l=l||function(a,b){return!!(a&&a.$classData&&a.$classData.k===b&&a.$classData.i.f[q])};h.t=f;h.f=c;h.p="L"+b+";";h.b=l;h.name=b;h.isInterface=!1;h.isRawJSType=!!d;h.isInstance=g;return h}
function ia(a){function b(a){if("number"===typeof a){this.z=Array(a);for(var b=0;b<a;b++)this.z[b]=f}else this.z=a}var c=new O,d=a.A,f="longZero"==d?R().u:d;b.prototype=new S;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.p,g=a.i||a,l=a.k+1;c.B=b;c.t=ja;c.f={a:1,V:1,c:1};c.l=a;c.i=g;c.k=l;c.A=null;c.p=d;c.o=void 0;c.n=void 0;c.b=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return g.b(a,l)};return c}
function x(a){if(!a.o){var b=new T;b.m=a;a.o=b}return a.o}O.prototype.getFakeInstance=function(){return this===y?"some string":this===G?!1:this===A||this===C||this===D||this===E||this===F?0:this===I?R().u:this===H?void 0:{$classData:this}};O.prototype.getSuperclass=function(){return this.t?x(this.t):null};O.prototype.getComponentType=function(){return this.l?x(this.l):null};O.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.n||(b.n=ia(b)),b=b.n;return w(b,a,0)};
var ka=P(!1,"Z","boolean"),la=P(0,"C","char"),ma=P(0,"B","byte"),na=P(0,"S","short"),oa=P(0,"I","int"),pa=P("longZero","J","long"),qa=P(0,"F","float"),ra=P(0,"D","double");ka.b=v(ka);la.b=v(la);ma.b=v(ma);na.b=v(na);oa.b=v(oa);pa.b=v(pa);qa.b=v(qa);ra.b=v(ra);function U(){}function S(){}S.prototype=U.prototype;U.prototype.d=function(){return this};U.prototype.y=function(){var a=ba(this).m.name,b=(+(this.w()>>>0)).toString(16);return a+"@"+b};U.prototype.w=function(){return ea(this)};U.prototype.toString=function(){return this.y()};var ja=Q({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.k||0;return!(c<b)&&(c>b||!a.i.isPrimitive)}return!1});U.prototype.$classData=ja;function V(){}
V.prototype=new S;V.prototype.constructor=V;V.prototype.d=function(){return this};V.prototype.$classData=Q({F:0},"mdocjs$",{F:1,a:1});var ta=void 0;function T(){this.m=null}T.prototype=new S;T.prototype.constructor=T;T.prototype.y=function(){return(this.m.isInterface?"interface ":this.m.isPrimitive?"":"class ")+this.m.name};T.prototype.$classData=Q({J:0},"java.lang.Class",{J:1,a:1});function M(){this.g=!1;this.C=this.r=this.j=null;this.v=!1;this.E=this.D=0}M.prototype=new S;
M.prototype.constructor=M;M.prototype.d=function(){L=this;this.j=(this.g=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.r=this.g?new k.Int32Array(this.j,0,2):null;this.g&&new k.Float32Array(this.j,0,2);this.C=this.g?new k.Float64Array(this.j,0,1):null;if(this.g)this.r[0]=16909060,a=1===((new k.Int8Array(this.j,0,8))[0]|0);else var a=!0;this.D=(this.v=a)?0:1;this.E=this.v?1:0;return this};
M.prototype.$classData=Q({P:0},"scala.scalajs.runtime.Bits$",{P:1,a:1});var L=void 0;function K(){}K.prototype=new S;K.prototype.constructor=K;K.prototype.d=function(){return this};K.prototype.$classData=Q({R:0},"scala.scalajs.runtime.RuntimeString$",{R:1,a:1});var ca=void 0;function W(){}W.prototype=new S;W.prototype.constructor=W;function ua(){}ua.prototype=W.prototype;
var H=Q({S:0},"scala.runtime.BoxedUnit",{S:1,a:1,c:1},void 0,void 0,function(a){return void 0===a}),G=Q({H:0},"java.lang.Boolean",{H:1,a:1,c:1,e:1},void 0,void 0,function(a){return"boolean"===typeof a});function X(){this.u=null}X.prototype=new S;X.prototype.constructor=X;X.prototype.d=function(){Y=this;this.u=N(0,0);return this};
function va(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+r(1E9)|0)-(0!==b?r(b):32+r(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,g=a,l=b;for(a=b=0;0<=c&&0!==(-2097152&l);){var h=g,q=l,sa=f,da=d;if(q===da?(-2147483648^h)>=(-2147483648^sa):(-2147483648^q)>=(-2147483648^da))h=l,q=d,l=g-f|0,h=(-2147483648^l)>(-2147483648^g)?-1+(h-q|0)|0:h-q|0,g=l,l=h,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;h=d>>>1|0;f=f>>>1|0|d<<31;d=h}c=l;if(0===c?-1147483648<=(-2147483648^
g):-2147483648<=(-2147483648^c))c=4294967296*l+ +(g>>>0),g=c/1E9,f=g/4294967296|0,d=b,b=g=d+(g|0)|0,a=(-2147483648^g)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}X.prototype.$classData=Q({Q:0},"scala.scalajs.runtime.RuntimeLong$",{Q:1,a:1,W:1,c:1});var Y=void 0;function R(){Y||(Y=(new X).d());return Y}
var y=Q({G:0},"java.lang.String",{G:1,a:1,c:1,U:1,e:1},void 0,void 0,function(a){return"string"===typeof a}),A=Q({I:0},"java.lang.Byte",{I:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return z(a)}),F=Q({K:0},"java.lang.Double",{K:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),E=Q({L:0},"java.lang.Float",{L:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),D=Q({M:0},"java.lang.Integer",{M:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),I=Q({N:0},"java.lang.Long",{N:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return!!(a&&a.$classData&&a.$classData.f.x)}),C=Q({O:0},"java.lang.Short",{O:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return B(a)});function Z(){this.q=this.s=0}Z.prototype=new ua;Z.prototype.constructor=Z;Z.prototype.y=function(){R();var a=this.s,b=this.q;return b===a>>31?""+a:0>b?"-"+va(-a|0,0!==a?~b:-b|0):va(a,b)};function N(a,b){var c=new Z;c.s=a;c.q=b;return c}
Z.prototype.w=function(){return this.s^this.q};Z.prototype.$classData=Q({x:0},"scala.scalajs.runtime.RuntimeLong",{x:1,h:1,a:1,c:1,e:1});m["mdoc-js-run0"]=function(){ta||(ta=(new V).d())};
